import Link from 'next/link';
import { Button } from '@/components/ui/button';

export default function Home() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero Section */}
      <div className="flex min-h-screen flex-col items-center justify-center px-4 py-12 md:px-6">
        <div className="w-full max-w-4xl space-y-12">
          {/* Title */}
          <div className="space-y-6 text-center">
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-black leading-tight">
              Find your next
              <br />
              app idea
            </h1>
            <p className="text-lg md:text-xl text-gray-600 max-w-2xl mx-auto">
              AI-powered idea discovery. Swipe through personalized suggestions.
              Save your favorites and get detailed implementation plans.
            </p>
          </div>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link href="/auth/signup" className="w-full sm:w-auto">
              <Button size="lg" className="w-full sm:w-auto min-w-[200px]">
                Get started
              </Button>
            </Link>
            <Link href="/auth/login" className="w-full sm:w-auto">
              <Button size="lg" variant="outline" className="w-full sm:w-auto min-w-[200px]">
                Sign in
              </Button>
            </Link>
          </div>

          {/* Features */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-12">
            <div className="text-center space-y-2">
              <div className="text-4xl">🤖</div>
              <h3 className="font-semibold text-black">AI-Powered</h3>
              <p className="text-sm text-gray-600">Get unique ideas generated by Google Gemini</p>
            </div>
            <div className="text-center space-y-2">
              <div className="text-4xl">👆</div>
              <h3 className="font-semibold text-black">Swipe to Explore</h3>
              <p className="text-sm text-gray-600">Tinder-style interface for browsing ideas</p>
            </div>
            <div className="text-center space-y-2">
              <div className="text-4xl">📋</div>
              <h3 className="font-semibold text-black">Detailed Plans</h3>
              <p className="text-sm text-gray-600">Implementation steps and tech recommendations</p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
